// LibraryMain.ts
//
// Owns: game orchestration for the mini library organizer — lifecycle,
// cross-cutting shelving decisions (which shelf/slot a released book maps
// to), and pushing state into the UI module. Delegates: per-book grab/lock
// mechanics to LibraryBookController, per-shelf slot occupancy to
// LibraryShelfController, progress counting to LibraryState, and all visible
// UI to LibraryOrganizerUI (never touches Component.Text directly).
//
// @input books: all 15 LibraryBookController instances (wired by the bootstrap).
// @input shelves: all 3 LibraryShelfController instances (wired by the bootstrap).
// @input ui: the LibraryOrganizerUI module (wired by the bootstrap).
// Must NOT build scene geometry or UI widgets itself — those are authored by
// the bootstrap / generated by their owning modules.

import { LibraryBookController } from "./LibraryBookController"
import { LibraryShelfController } from "./LibraryShelfController"
import { LibraryOrganizerUI } from "./LibraryOrganizerUI"
import { LibraryState } from "./LibraryState"

@component
export class LibraryMain extends BaseScriptComponent {
  @ui.label('<span style="color: #60A5FA;">LibraryMain – library organizer orchestrator</span>')
  @ui.separator
  @ui.group_start("References")
  @input
  @hint("All 15 book controllers scattered on the floor at start.")
  books: LibraryBookController[] = []

  @input
  @hint("All 3 shelf controllers (red, green, blue).")
  shelves: LibraryShelfController[] = []

  @input
  @hint("The progress HUD + completion dialog UI module.")
  ui!: LibraryOrganizerUI
  @ui.group_end

  private state!: LibraryState

  onAwake() {
    if (!this.ui) {
      print("LibraryMain: 'ui' input not wired — check the scene bootstrap.")
    }
    if (this.books.length === 0) {
      print("LibraryMain: 'books' input not wired — check the scene bootstrap.")
    }
    if (this.shelves.length === 0) {
      print("LibraryMain: 'shelves' input not wired — check the scene bootstrap.")
    }

    this.state = new LibraryState(this.books.length)
    this.state.onProgressChanged.add(({ shelved, total }) => {
      if (this.ui) this.ui.setProgress(shelved, total)
    })
    this.state.onComplete.add(() => {
      if (this.ui) {
        this.ui.stopTimer()
        this.ui.showComplete()
      }
    })

    this.createEvent("OnStartEvent").bind(() => {
      // Deferred to OnStartEvent: LibraryMain sits at the scene root and runs
      // its onAwake before the books further down the hierarchy run theirs,
      // so book.onReleased isn't guaranteed to exist yet in onAwake. All
      // onAwake calls scene-wide complete before any OnStartEvent fires, so
      // it's safe here.
      for (const book of this.books) {
        book.onReleased.add((releasedBook) => this.handleBookReleased(releasedBook))
      }

      if (this.ui) {
        this.ui.onResetRequested.add(() => this.resetGame())
        this.ui.setProgress(this.state.getShelved(), this.state.total)
        // Do NOT call ui.hideComplete() here: the dialog's own Frame
        // component starts hidden itself, on its own first-time
        // initialization (see LibraryOrganizerUI.buildCompleteDialog). A
        // disabled SceneObject's OnStartEvent is deferred until it is next
        // enabled, so disabling the dialog from here — before its own
        // OnStartEvent has had a chance to run Frame's one-time init — was
        // preventing that init from EVER happening at load. It would only
        // fire later, the moment showComplete() re-enabled it at game
        // completion, whose own "start hidden" step then immediately
        // re-hid the dialog right after showing it.
      }
    })
  }

  private handleBookReleased(book: LibraryBookController): void {
    if (book.isLocked()) return
    const bookPos = book.getTransform().getWorldPosition()

    for (const shelf of this.shelves) {
      if (!shelf.isNearShelf(bookPos)) continue

      if (shelf.getColorId() !== book.getColorId()) {
        book.rejectPlacement()
        return
      }

      const slot = shelf.claimNearestFreeSlot(bookPos)
      if (!slot) {
        // Shelf's 5 slots are already full — treat as a reject.
        book.rejectPlacement()
        return
      }

      book.lockToSlot(slot.getTransform().getWorldPosition(), slot.getTransform().getWorldRotation())
      this.state.incrementShelved()
      return
    }
    // Not near any shelf — leave the book exactly where it was released.
  }

  private resetGame(): void {
    for (const book of this.books) book.resetToOriginal()
    for (const shelf of this.shelves) shelf.resetSlots()
    this.state.reset()
    if (this.ui) {
      this.ui.hideComplete()
      // Replaying is a fresh timed attempt — restart the clock immediately
      // rather than waiting for a "start" gesture that doesn't exist on replay.
      this.ui.startTimer()
    }
  }
}
